modLoader="javafml"
loaderVersion="[36,)"


# https://choosealicense.com/
license="GNU General Public License v3.0"

issueTrackerURL="https://github.com/kpzip/slime_revolution/issues"
[[mods]]
modId="slimerevolution"
version="${file.jarVersion}"
displayName="Slime Revolution"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/kpzip/slime_revolution"
logoFile="logo.png"

#credits=""
authors="Kyle `kpzip` Schmerge and Yegor `yeg_` Tryndin" #optional
description='''
Slime Revolution is a mod that adds machines and progression based on the material slime.
The name `Slime Revolution` refers to the Industrial Revolution if it used slime instead of things like oil and metal.
'''

[[dependencies.slimerevolution]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.slimerevolution]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
